Dennie view blog entry
Underdog-Devs/website-v2 pull request #16
Opened 2022-05-02 00:12 UTC by DennieCodes

## Description ##

Added Blog folder, index.tsx, blog.module.scss.  

Create View blog entry page with dummy blog info for now and image placeholders or dummy images.

## Screen shots or GIFs of UI changes ##

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing-

## Checklist ##

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [ ] Looks good on large screens
- [ ] Looks good on mobile

## Organization ##

- [ ] Have you linked this pull request to a [project ticket](https://github.com/Underdog-Devs/website/projects/2)? 

## Review ##

- [ ] Is this a work in progress?
- [ ] Is this ready to be reviewed?
- [ ] Have you added two reviewers to this pull request?

2022-05-02 00:16 UTC, UnderdogDevsIntake commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create View blog entry page with dummy blog info for now and image placeholders or dummy images](https://trello.com/c/RtkJjleR/27-create-view-blog-entry-page-with-dummy-blog-info-for-now-and-image-placeholders-or-dummy-images)

2022-05-02 00:33 UTC, UnderdogDevsIntake requested changes
I've added a few mostly styling comments for you to address before merge but this is looking really great so far!

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/index.tsx
> +import React from 'react';
Please move this code into a new file called `Blog.tsx` in this same directory and inside the `index.ts` add the code `export * from './Blog'`

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/index.tsx
> +const Blog = () => {
lets change this line to `export const Blog`

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/index.tsx
> +export default Blog;
lets remove this line entirely since now we're creating a named export

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +	p {
the `p` tag appears after the `header` and `h3` in the `jsx` structure so lets move this down in the styles to match its position in the `jsx`

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +
lets use our `$textBlack`  variable in this file for the font color so we're not using the default browser black

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +		position: relative;
lets use `flexbox` for positioning items on the page this way when we add responsive styles the layout will be a little more fluid

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +			position: absolute;
see comment about using `flexbox`

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +		display: inline-block;
see comment about using flexbox

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +			float: right;
see comment about using `flexbox`

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +			width: 17em;
lets use `pixels` when working with `height` and `width` to keep consistent with the rest of the site

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +		border-top: 1px solid black;
lets stay away from using black and go with our variable `$textBlack`

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +		border-bottom: 1px solid black;
same here for replacing the black border with the `$textBlack` variable

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +
this would be an ideal place for the `p` styles mentioned above to live

2022-05-02 00:33 UTC, UnderdogDevsIntake commented on pages/blog/blog.module.scss
> +		p {
lets move this under the `blogThumbnail` styles to keep consistent with the `jsx` structure

2022-05-07 20:52 UTC, JessBonanno commented
Checking in on the status of the updates requested.  Also noticed that the layout does not match the figma spec.  The layout should not take up the full width of the screen see screen shots:
![Screen Shot 2022-05-07 at 4 50 13 PM](https://user-images.githubusercontent.com/58790413/167271342-b128e8bf-f43a-4a5e-b95e-86451feada46.png)
![Screen Shot 2022-05-07 at 4 49 44 PM](https://user-images.githubusercontent.com/58790413/167271343-781046a1-4859-4b77-b075-6b2f6751e05a.png)

2022-05-30 20:44 UTC, UnderdogDevsIntake commented
Please also resolve merge conflicts with a rebase

2022-05-30 21:08 UTC, UnderdogDevsIntake commented
This PR still has changes requested that need to be addressed and also this PR needs to be closed and reopened against development instead of main as outlined in our git flow documentation.

2022-05-30 21:08 UTC, closed without merging