Caleb testimonial page
Underdog-Devs/website-v2 pull request #17
Opened 2022-05-04 03:02 UTC by cvance248

## Description ##

DESCRIBE YOUR PULL REQUEST'S CHANGES.  Created testimonial page and added testimonial link to header for all screen sizes. made the testimonial content responsive also.

## Screen shots or GIFs of UI changes ##

![Image 5-3-22 at 10 56 PM](https://user-images.githubusercontent.com/37356219/166617794-7b4b43e5-b0f8-44c9-916a-2f5c247dc201.jpeg)

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing-

## Checklist ##

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [ x] Looks good on large screens
- [ x] Looks good on mobile

## Organization ##

- [ ] Have you linked this pull request to a [project ticket](https://github.com/Underdog-Devs/website/projects/2)? 

## Review ##

- [ ] Is this a work in progress?
- [ x] Is this ready to be reviewed?
- [x ] Have you added two reviewers to this pull request?

2022-05-04 03:03 UTC, cvance248 commented
![](https://github.trello.services/images/mini-trello-icon.png) [create testimonials page with header](https://trello.com/c/XM4dGt9q/31-create-testimonials-page-with-header)

2022-05-07 21:02 UTC, JessBonanno requested changes
Great work, I left a few requests for changes but looking great so far!

2022-05-07 21:02 UTC, JessBonanno commented on pages/testimonials/testimonials.module.scss
> +        p {
lets update these `p` tag styles to be `.testimonial` styles once you change the `p` tags to `divs`

2022-05-07 21:02 UTC, JessBonanno commented on pages/testimonials/testimonials.module.scss
> +            border: black 3px solid;
these `border` styles are fine for now until we insert the testimonial components

2022-05-30 21:07 UTC, UnderdogDevsIntake commented
this PR needs to be closed and reopened against the development branch instead of main as outlined in the documentation in our source of truth please

2022-05-30 21:07 UTC, closed without merging